functionality:
  name: "process_datasets"
  namespace: "workflows"
  version: "main_build"
  argument_groups:
  - name: "Inputs"
    arguments:
    - type: "file"
      name: "--input"
      info:
        label: "Common Dataset"
        summary: "A subset of the common dataset."
        slots:
          layers:
          - type: "integer"
            name: "counts"
            description: "Raw counts."
            required: true
          obs:
          - type: "string"
            name: "cell_type"
            description: "Cell type label IDs."
            required: true
          - type: "string"
            name: "batch"
            description: "A batch identifier. This label is very context-dependent\
              \ and may be a combination of the tissue, assay, donor, etc."
            required: true
          var:
          - type: "boolean"
            name: "hvg"
            description: "Whether or not the feature is considered to be a 'highly\
              \ variable gene'"
            required: true
          - type: "double"
            name: "hvg_score"
            description: "A ranking of the features by hvg."
            required: true
          obsm:
          - type: "double"
            name: "X_pca"
            description: "The resulting PCA embedding."
            required: true
          - type: "double"
            name: "coordinates"
            description: "XY coordinates for each spot."
            required: false
          - type: "double"
            name: "proportions_true"
            description: "True cell type proportions for each spot"
            required: false
          uns:
          - type: "string"
            name: "cell_type_names"
            description: "Cell type names corresponding to values in `cell_type`"
            required: false
          - type: "string"
            name: "dataset_id"
            description: "A unique identifier for the dataset"
            required: true
          - name: "dataset_name"
            type: "string"
            description: "Nicely formatted name."
            required: true
          - type: "string"
            name: "dataset_url"
            description: "Link to the original source of the dataset."
            required: false
          - name: "dataset_reference"
            type: "string"
            description: "Bibtex reference of the paper in which the dataset was published."
            required: false
          - name: "dataset_summary"
            type: "string"
            description: "Short description of the dataset."
            required: true
          - name: "dataset_description"
            type: "string"
            description: "Long description of the dataset."
            required: true
          - name: "dataset_organism"
            type: "string"
            description: "The organism of the sample in the dataset."
            required: false
      example:
      - "resources_test/spatial_decomposition/cxg_mouse_pancreas_atlas/dataset_simulated.h5ad"
      must_exist: true
      create_parent: true
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "double"
      name: "--alpha"
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Outputs"
    arguments:
    - type: "file"
      name: "--output_single_cell"
      info:
        label: "Single cell data"
        summary: "The single-cell data file used as reference for the spatial data"
        slots:
          layers:
          - type: "integer"
            name: "counts"
            description: "Raw counts"
            required: true
          obs:
          - type: "string"
            name: "cell_type"
            description: "Cell type label IDs"
            required: true
          - type: "string"
            name: "batch"
            description: "A batch identifier. This label is very context-dependent\
              \ and may be a combination of the tissue, assay, donor, etc."
            required: false
          uns:
          - type: "string"
            name: "cell_type_names"
            description: "Cell type names corresponding to values in `cell_type`"
            required: true
          - type: "string"
            name: "dataset_id"
            description: "A unique identifier for the dataset"
            required: true
      example:
      - "resources_test/spatial_decomposition/cxg_mouse_pancreas_atlas/single_cell_ref.h5ad"
      must_exist: true
      create_parent: true
      required: true
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--output_spatial_masked"
      info:
        label: "Spatial masked"
        summary: "The spatial data file containing transcription profiles for each\
          \ capture location, without cell-type proportions for each spot."
        slots:
          layers:
          - type: "integer"
            name: "counts"
            description: "Raw counts"
            required: true
          obsm:
          - type: "double"
            name: "coordinates"
            description: "XY coordinates for each spot"
            required: true
          uns:
          - type: "string"
            name: "cell_type_names"
            description: "Cell type names corresponding to columns of `proportions_pred`\
              \ in output"
            required: true
          - type: "string"
            name: "dataset_id"
            description: "A unique identifier for the dataset"
            required: true
      example:
      - "resources_test/spatial_decomposition/cxg_mouse_pancreas_atlas/spatial_masked.h5ad"
      must_exist: true
      create_parent: true
      required: true
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--output_solution"
      info:
        label: "Solution"
        summary: "The spatial data file containing transcription profiles for each\
          \ capture location, with true cell-type proportions for each spot / capture\
          \ location."
        slots:
          layers:
          - type: "integer"
            name: "counts"
            description: "Raw counts"
            required: true
          obsm:
          - type: "double"
            name: "coordinates"
            description: "XY coordinates for each spot"
            required: true
          - type: "double"
            name: "proportions_true"
            description: "True cell type proportions for each spot"
            required: true
          uns:
          - name: "cell_type_names"
            type: "string"
            description: "Cell type names corresponding to columns of `proportions`"
            required: true
          - name: "dataset_id"
            type: "string"
            description: "A unique identifier for the dataset"
            required: true
          - name: "dataset_name"
            type: "string"
            description: "Nicely formatted name."
            required: true
          - type: "string"
            name: "dataset_url"
            description: "Link to the original source of the dataset."
            required: false
          - name: "dataset_reference"
            type: "string"
            description: "Bibtex reference of the paper in which the dataset was published."
            required: false
          - name: "dataset_summary"
            type: "string"
            description: "Short description of the dataset."
            required: true
          - name: "dataset_description"
            type: "string"
            description: "Long description of the dataset."
            required: true
          - name: "dataset_organism"
            type: "string"
            description: "The organism of the sample in the dataset."
            required: false
          - type: "string"
            name: "normalization_id"
            description: "Which normalization was used"
            required: true
      example:
      - "resources_test/spatial_decomposition/cxg_mouse_pancreas_atlas/solution.h5ad"
      must_exist: true
      create_parent: true
      required: true
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--simulated_data"
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  resources:
  - type: "nextflow_script"
    path: "main.nf"
    is_executable: true
    entrypoint: "run_wf"
  - type: "file"
    path: "common/nextflow_helpers/helper.nf"
  info: null
  status: "enabled"
  dependencies:
  - name: "common/check_dataset_schema"
    repository:
      type: "github"
      name: ""
      repo: "openproblems-bio/openproblems-v2"
      tag: "main_build"
      localPath: "/tmp/viash_hub_repo12794244047844385383"
    foundConfigPath: "/tmp/viash_hub_repo12794244047844385383/target/nextflow/common/check_dataset_schema/.config.vsh.yaml"
    configInfo:
      functionalityName: "check_dataset_schema"
      git_remote: "https://github.com/openproblems-bio/openproblems-v2"
      viash_version: "0.8.0"
      config: "/home/runner/work/openproblems-v2/openproblems-v2/src/common/check_dataset_schema/config.vsh.yaml"
      functionalityNamespace: "common"
      output: "/home/runner/work/openproblems-v2/openproblems-v2/target/nextflow/common/check_dataset_schema"
      platform: "nextflow"
      git_commit: "d0bc03fb05d43fb26f51c6fe6aa2e2a2f7ff5ade"
      executable: "/home/runner/work/openproblems-v2/openproblems-v2/target/nextflow/common/check_dataset_schema/check_dataset_schema"
    writtenPath: "/home/runner/work/task-spatial-decomposition/task-spatial-decomposition/target/dependencies/github/openproblems-bio/openproblems-v2/main_build/nextflow/common/check_dataset_schema"
  - name: "dataset_simulator"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/task-spatial-decomposition/task-spatial-decomposition/src/dataset_simulator/config.vsh.yaml"
    configInfo:
      functionalityName: "dataset_simulator"
      git_tag: ""
      git_remote: "https://github.com/openproblems-bio/task-spatial-decomposition"
      viash_version: "0.8.6"
      config: "/home/runner/work/task-spatial-decomposition/task-spatial-decomposition/src/dataset_simulator/config.vsh.yaml"
      functionalityNamespace: ""
      output: ""
      platform: ""
      git_commit: "aa8ff5245a3c0c3fd1ce8b64421720a51518c7e2"
      executable: "/nextflow/dataset_simulator/main.nf"
    writtenPath: "/home/runner/work/task-spatial-decomposition/task-spatial-decomposition/target/nextflow/dataset_simulator"
  - name: "process_dataset/split_dataset"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/task-spatial-decomposition/task-spatial-decomposition/src/process_dataset/split_dataset/config.vsh.yaml"
    configInfo:
      functionalityName: "split_dataset"
      git_tag: ""
      git_remote: "https://github.com/openproblems-bio/task-spatial-decomposition"
      viash_version: "0.8.6"
      config: "/home/runner/work/task-spatial-decomposition/task-spatial-decomposition/src/process_dataset/split_dataset/config.vsh.yaml"
      functionalityNamespace: "process_dataset"
      output: ""
      platform: ""
      git_commit: "aa8ff5245a3c0c3fd1ce8b64421720a51518c7e2"
      executable: "/nextflow/process_dataset/split_dataset/main.nf"
    writtenPath: "/home/runner/work/task-spatial-decomposition/task-spatial-decomposition/target/nextflow/process_dataset/split_dataset"
  repositories:
  - type: "github"
    name: "openproblems_v2"
    repo: "openproblems-bio/openproblems-v2"
    tag: "main_build"
    localPath: ""
  set_wd_to_resources_dir: false
platforms:
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      veryhightime: "time = 24.h"
    script:
    - "process.errorStrategy = 'ignore'"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/task-spatial-decomposition/task-spatial-decomposition/src/workflows/process_datasets/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/task-spatial-decomposition/task-spatial-decomposition/target/nextflow/workflows/process_datasets"
  executable: "/home/runner/work/task-spatial-decomposition/task-spatial-decomposition/target/nextflow/workflows/process_datasets/main.nf"
  viash_version: "0.8.6"
  git_commit: "aa8ff5245a3c0c3fd1ce8b64421720a51518c7e2"
  git_remote: "https://github.com/openproblems-bio/task-spatial-decomposition"
