__merge__: ../api/comp_process_dataset.yaml
functionality:
  name: "process_dataset"
  resources:
    - type: python_script
      path: script.py
    - path: /../openproblems-v2/src/common/helper_functions/subset_anndata.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
  - type: nextflow
    directives: 
      label: [midtime, highmem, highcpu]
